// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package proto.employee;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.employee.Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *employee_id;name;building_code;floor_number;salary;department
   * </pre>
   *
   * <code>int32 employee_id = 1;</code>
   * @return The employeeId.
   */
  int getEmployeeId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 building_code = 3;</code>
   * @return The buildingCode.
   */
  int getBuildingCode();

  /**
   * <code>.proto.employee.Floor floor_number = 4;</code>
   * @return The enum numeric value on the wire for floorNumber.
   */
  int getFloorNumberValue();
  /**
   * <code>.proto.employee.Floor floor_number = 4;</code>
   * @return The floorNumber.
   */
  proto.employee.Floor getFloorNumber();

  /**
   * <code>int32 salary = 5;</code>
   * @return The salary.
   */
  int getSalary();

  /**
   * <code>string department = 6;</code>
   * @return The department.
   */
  java.lang.String getDepartment();
  /**
   * <code>string department = 6;</code>
   * @return The bytes for department.
   */
  com.google.protobuf.ByteString
      getDepartmentBytes();

  /**
   * <code>int32 cafeteria_code = 7;</code>
   * @return The cafeteriaCode.
   */
  int getCafeteriaCode();
}
